name: Cypass test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Install Dependencies
        run: npm ci

      - name: Cypress Install
        run: npx cypress install
        #working-directory: CUSTOMAP/project/client

      - name: Cypress Run
        run: npm run cy:run
        # uses: cypress-io/github-action@v6
        # with:
        #working-directory: project/client

      - name: Save Test Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: cypress/screenshots

      - name: Save Test Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: cypress/videos
