# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: testing & CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

  cypress_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install Dependencies
      run: npm ci

    - name: Cypress Install
      run: npx cypress install

    - name: Cypress Run
      run: npm run cy:run
        
  jest_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install Dependencies
      run: npm i supertest
           npm i jest
           npm i cookie
           npm i express
           npm i cors
           npm i cookie-parser
           npm i jsonwebtoken
           npm i mongoose
           npm i bcryptjs
           npm i ts-node
        
    - name: Test
      run: npm test
    
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU }}
          heroku_app_name: 'customap416client'
          heroku_email: 'shihao.wen@stonybrook.edu'
          justlogin: true
