# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: testing & CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{ secrets.HEROKU }}
          heroku_app_name: 'customap416client'
          heroku_email: 'shihao.wen@stonybrook.edu'
