name: Testing & CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build --if-present

      - name: Install Dependencies
        run: npm ci
  
      - name: Cypress Install
        run: npx cypress install

      - name: Install Dependencies
        run: npm i supertest
             npm i jest
             npm i cookie
             npm i express
             npm i cors
             npm i cookie-parser
             npm i jsonwebtoken
             npm i mongoose
             npm i bcryptjs
             npm i ts-node
          
    

  jest_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test
        run: npm test
      
  cypress_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cypress Run
        run: npm run cy:run
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU }}
          heroku_app_name: 'customap416client'
          heroku_email: 'shihao.wen@stonybrook.edu'
          justlogin: true
